const LOADING_ERROR = "LOADING_ERROR";
const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
const LOADING_SUCCESS = "LOADING_SUCCESS";
const CLEAR_ARTICLES = "CLEAR_ARTICLES";

export { LOADING_ERROR, LOADING_IN_PROGRESS, LOADING_SUCCESS, CLEAR_ARTICLES };
